name : First git action workflow

on :
 push :
  branches:
     'main'

jobs :
  test :
    name : Test Example
    runs-on : ubuntu-latest

    steps :
    - name : checkout
      uses : actions/checkout@v1
    
    - name : run pom file
      run : mvn test

    - if : always()
      run : |
           ls
           cd target/surefire-reports
           ls -l

    - if : always()
      uses : actions/upload-artifact@master
      with :
       name : automationReport.html
       path : ./target/surefire-reports/index.html
