name : First git action workflow

on :
 push :
  branches:
     'main'
 workflow_dispatch:

jobs :
  test :
    name : Test Example
    runs-on : ubuntu-latest

    steps :
    - name : checkout
      uses : actions/checkout@v2
    
    - name : run pom file
      run : mvn test

    - if : always()
      run : |
            cd target
            cd ..
            ls -l
            cd report
          

    - if : always()
      uses : actions/upload-artifact@master
      with :
       name : automationReport.html
       path : ./report/TestReport*.html
